# Generated by Django 4.2.11 on 2024-04-26 09:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('face_detection', '0002_remove_attendancemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancemodel',
            unique_together={('user', 'date_came')},
        ),
    ]
